Repository IETS3/iets3.opensource, pull requests merged in 2023-02, with the labels that each got.

#633 [minor] Typesystem: handle cases where computeSupertype returns an error
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/typesystem.mps
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/typesystem.mps
Labels: PRIO

#625 Improve dark themes support for tables
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.editor.mps
Labels: PRIO

#644 Make the function runSolver virtual to overwrite it where necessary
  code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/behavior.mps
Labels: minor

#640 Bugfix/correct sum op
  code/languages/org.iets3.opensource/.mps/modules.xml
  code/languages/org.iets3.opensource/devkits/org.iets3.core.expr.genjava.core.devkit/org.iets3.core.expr.genjava.core.devkit.devkit
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/org.iets3.core.expr.genjava.simpleTypes.mpl
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.stateMachineExample/sandbox/org.iets3.core.expr.genjava.stateMachineExample.sandbox.msd
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.tests/org.iets3.core.expr.genjava.tests.mpl
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/org.iets3.core.expr.genjava.toplevel.mpl
  code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps
  code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/org.iets3.core.expr.collections.interpreter.msd
  code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.rt/models/org.iets3.core.expr.collections.rt.rt.mps
  code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.rt/org.iets3.core.expr.collections.rt.msd
  code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.base.rt/models/rt.mps
  code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.stringvalidation.interpreter/models/org.iets3.core.expr.stringvalidation.interpreter.plugin.mps
  code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
  code/languages/org.iets3.opensource/solutions/test.ex.core.expr.genjava/test.ex.core.expr.genjava.msd
  code/languages/org.iets3.opensource/tests/test.in.expr.os/test.in.expr.os.msd
Labels: PRIO, minor

#637 Add a type to the field of FieldSetter
  code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/typesystem.mps
Labels: PRIO, minor

#653 Make the method runSolverAsync virtual.
  code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/behavior.mps
Labels: minor

#650 Expr plugin: reduce command to read access in InterpreterUserObjectDecorator
  code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps
Labels: PRIO
